import type {
  ClimateMarket,
  MarketEvidence,
  MarketHistoryPoint,
  MarketTrade,
  TradeSide,
  UserActivity,
  UserPosition,
} from "./types"

export const DEMO_DATA_DISCLAIMER =
  "SAMPLE DATA — This market, its probabilities, trades, evidence summaries, and pool liquidity are fictional Devnet demonstration data."

export const DEMO_WALLETS = {
  atlas: "Udf5rTTTfiQGstoHtf6TsUfo9zHjN2zjo9kF49vebzH",
  boreal: "2HfCoU3aZFH7wxttXUa7xNjpj49P6KdMwwFvx6MpcRos",
  cirrus: "3mshx6HoZop71xQ483kLMdiUuXQ1UxDgBABuLnFkVfDV",
} as const

const DEMO_SIGNATURES = [
  "4a4iVL4tfH6mDmM2DBGN7R9Qs6Br5Je7rFEPZKzUQjQ1zutf2JJQApLCXbsLGoLjCifyj69uoibFnFUV7PFydUd",
  "DtEQdfYhAXMo6iWP25G8SnxjoUe3nZjWunhKj3n2mX9wYEGpLnhLiFzzvpgTo8fFCYGB73F1KtbSdrgVfk7HGNV",
  "aqcDTRNkJKwcprcwLbCSkXWyUKBXGmYA63iJrEwksaXg5zte76RQ6b2HEXNJp4QQ1tpqWVXaYGtYu2F9mjDuTRM",
  "24n7HtRp9p4iiTi6zhbBzfD2jtWGMSsbX1LWnwLXkxoJYZc7jPn7REEwsuDMttdD94JDVRyXggZy4FVmUEjrPw6j",
] as const

const round = (value: number, places = 2): number => {
  const factor = 10 ** places
  return Math.round(value * factor) / factor
}

interface HistoryOptions {
  start: string
  yesProbabilities: readonly number[]
  baseLiquidity: number
  baseVolume: number
  liquidityStep?: number
  volumeStep?: number
  cadenceDays?: number
}

export const buildHistory = ({
  start,
  yesProbabilities,
  baseLiquidity,
  baseVolume,
  liquidityStep = 18,
  volumeStep = 31,
  cadenceDays = 14,
}: HistoryOptions): MarketHistoryPoint[] => {
  const startTime = Date.parse(start)

  return yesProbabilities.map((yesProbability, index) => {
    const totalLiquidity = baseLiquidity + liquidityStep * index
    const yesLiquidity = round(totalLiquidity * yesProbability)
    const noLiquidity = round(totalLiquidity - yesLiquidity)

    return {
      timestamp: new Date(
        startTime + index * cadenceDays * 86_400_000,
      ).toISOString(),
      yesProbability,
      noProbability: round(1 - yesProbability, 4),
      totalVolume: round(baseVolume + volumeStep * index),
      yesLiquidity,
      noLiquidity,
      dataLabel: "SAMPLE DATA",
    }
  })
}

type DemoTradeInput = readonly [
  side: TradeSide,
  amountSol: number,
  probability: number,
  timestamp: string,
]

export const buildTrades = (
  marketId: string,
  inputs: readonly DemoTradeInput[],
): MarketTrade[] =>
  inputs.map(([side, amountSol, probability, timestamp], index) => ({
    id: `${marketId}-trade-${index + 1}`,
    marketId,
    side,
    amountSol,
    amountLamports: Math.round(amountSol * 1_000_000_000).toString(),
    probability,
    estimatedPayoutSol: round(amountSol / probability, 4),
    wallet:
      Object.values(DEMO_WALLETS)[index % Object.values(DEMO_WALLETS).length]!,
    timestamp,
    transactionSignature: DEMO_SIGNATURES[index % DEMO_SIGNATURES.length],
    isDemo: true,
  }))

interface EvidenceOptions {
  marketId: string
  publisher: string
  sourceUrl: string
  sourceTitle: string
  methodologyUrl: string
  methodologyTitle: string
  publishedAt: string
}

const buildEvidence = ({
  marketId,
  publisher,
  sourceUrl,
  sourceTitle,
  methodologyUrl,
  methodologyTitle,
  publishedAt,
}: EvidenceOptions): MarketEvidence[] => [
  {
    id: `${marketId}-evidence-source`,
    title: sourceTitle,
    summary:
      "Official source proposed for eventual resolution. No live observation from this source is embedded in the seeded probability.",
    publisher,
    url: sourceUrl,
    publishedAt,
    kind: "resolution-source",
    isDemo: true,
  },
  {
    id: `${marketId}-evidence-method`,
    title: methodologyTitle,
    summary:
      "Background methodology link for evaluating the rule. The market history and trade activity shown here remain fictional sample data.",
    publisher,
    url: methodologyUrl,
    publishedAt,
    kind: "methodology",
    isDemo: true,
  },
]

export const demoMarkets: ClimateMarket[] = [
  {
    id: "demo-fl-hurricane-2026",
    onchainMarketId: 1001,
    question:
      "[DEMO] Will Florida record a Category 4+ hurricane landfall before October 31, 2026?",
    slug: "florida-category-4-hurricane-2026-demo",
    description:
      "A fictional sample market tracking whether a hurricane classified as Category 4 or higher makes landfall in Florida during the stated window.",
    category: "hurricane",
    continent: "North America",
    country: "United States",
    region: "Florida",
    latitude: 27.6648,
    longitude: -81.5158,
    closeTime: "2026-10-31T23:59:59.000Z",
    resolutionTime: "2026-11-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.43,
    noPrice: 0.57,
    yesLiquidity: 430,
    noLiquidity: 570,
    totalVolume: 2_840,
    participants: 184,
    resolutionSource: "NOAA National Hurricane Center archive",
    resolutionSourceUrl: "https://www.nhc.noaa.gov/data/",
    resolutionRules:
      "Resolve YES if the NOAA post-season archive identifies a Category 4 or 5 hurricane landfall within Florida before the close time; otherwise resolve NO. Cancel if the designated archive is unavailable for 30 days.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-01T14:00:00.000Z",
    featured: true,
    trendingScore: 96,
    history: buildHistory({
      start: "2026-05-01T00:00:00.000Z",
      yesProbabilities: [0.31, 0.34, 0.32, 0.37, 0.41, 0.39, 0.43],
      baseLiquidity: 510,
      baseVolume: 650,
      liquidityStep: 81.67,
      volumeStep: 365,
    }),
    evidence: buildEvidence({
      marketId: "demo-fl-hurricane-2026",
      publisher: "NOAA National Hurricane Center",
      sourceUrl: "https://www.nhc.noaa.gov/data/",
      sourceTitle: "NHC hurricane archive (proposed resolution source)",
      methodologyUrl: "https://www.nhc.noaa.gov/aboutsshws.php",
      methodologyTitle: "Saffir-Simpson Hurricane Wind Scale",
      publishedAt: "2026-05-01T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-fl-hurricane-2026", [
      ["yes", 2.4, 0.43, "2026-07-17T16:20:00.000Z"],
      ["no", 1.1, 0.58, "2026-07-17T12:05:00.000Z"],
      ["yes", 0.75, 0.41, "2026-07-16T21:42:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-ca-drought-2026",
    onchainMarketId: 1002,
    question:
      "[DEMO] Will California enter severe drought conditions before December 31, 2026?",
    slug: "california-severe-drought-2026-demo",
    description:
      "A fictional sample market based on whether a defined share of California reaches the severe-drought threshold during 2026.",
    category: "drought",
    continent: "North America",
    country: "United States",
    region: "California",
    latitude: 36.7783,
    longitude: -119.4179,
    closeTime: "2026-12-31T23:59:59.000Z",
    resolutionTime: "2027-01-14T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.62,
    noPrice: 0.38,
    yesLiquidity: 775,
    noLiquidity: 475,
    totalVolume: 3_920,
    participants: 241,
    resolutionSource: "U.S. Drought Monitor California archive",
    resolutionSourceUrl:
      "https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?CA",
    resolutionRules:
      "Resolve YES if the designated weekly archive shows at least 25% of California in D2 (Severe Drought) or worse on any release before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-04-15T14:00:00.000Z",
    featured: true,
    trendingScore: 91,
    history: buildHistory({
      start: "2026-04-15T00:00:00.000Z",
      yesProbabilities: [0.48, 0.51, 0.56, 0.58, 0.55, 0.59, 0.62],
      baseLiquidity: 650,
      baseVolume: 840,
      liquidityStep: 100,
      volumeStep: 513.33,
    }),
    evidence: buildEvidence({
      marketId: "demo-ca-drought-2026",
      publisher: "U.S. Drought Monitor",
      sourceUrl:
        "https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?CA",
      sourceTitle:
        "California drought map archive (proposed resolution source)",
      methodologyUrl:
        "https://droughtmonitor.unl.edu/About/AbouttheData/DroughtClassification.aspx",
      methodologyTitle: "Drought classification methodology",
      publishedAt: "2026-04-15T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-ca-drought-2026", [
      ["yes", 3.5, 0.62, "2026-07-18T01:10:00.000Z"],
      ["no", 1.8, 0.39, "2026-07-17T18:33:00.000Z"],
      ["yes", 0.9, 0.6, "2026-07-17T08:15:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-ontario-rainfall-june-2026",
    onchainMarketId: 1003,
    question:
      "[DEMO] Did southern Ontario rainfall exceed its June historical average in 2026?",
    slug: "southern-ontario-june-rainfall-2026-demo",
    description:
      "A closed fictional sample market awaiting its authorized resolver's comparison of a designated regional rainfall index.",
    category: "rainfall",
    continent: "North America",
    country: "Canada",
    region: "Southern Ontario",
    latitude: 43.6532,
    longitude: -79.3832,
    closeTime: "2026-06-30T23:59:59.000Z",
    resolutionTime: "2026-07-25T18:00:00.000Z",
    status: "closed",
    outcome: "unresolved",
    yesPrice: 0.54,
    noPrice: 0.46,
    yesLiquidity: 378,
    noLiquidity: 322,
    totalVolume: 1_680,
    participants: 109,
    resolutionSource: "Environment and Climate Change Canada climate data",
    resolutionSourceUrl: "https://climate.weather.gc.ca/",
    resolutionRules:
      "Resolve YES if the arithmetic mean of June precipitation at the five listed reference stations exceeds the published 1991–2020 normal; otherwise NO. Station list is fixed in the demo metadata.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-03-15T14:00:00.000Z",
    featured: false,
    trendingScore: 67,
    history: buildHistory({
      start: "2026-03-15T00:00:00.000Z",
      yesProbabilities: [0.45, 0.47, 0.49, 0.52, 0.58, 0.56, 0.54],
      baseLiquidity: 370,
      baseVolume: 330,
      liquidityStep: 55,
      volumeStep: 225,
      cadenceDays: 17,
    }),
    evidence: buildEvidence({
      marketId: "demo-ontario-rainfall-june-2026",
      publisher: "Environment and Climate Change Canada",
      sourceUrl: "https://climate.weather.gc.ca/",
      sourceTitle: "Historical Canadian climate data portal",
      methodologyUrl: "https://climate.weather.gc.ca/climate_normals/",
      methodologyTitle: "Canadian climate normals portal",
      publishedAt: "2026-03-15T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-ontario-rainfall-june-2026", [
      ["yes", 1.2, 0.54, "2026-06-30T20:10:00.000Z"],
      ["no", 2.1, 0.47, "2026-06-30T14:45:00.000Z"],
      ["yes", 0.5, 0.52, "2026-06-29T22:30:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-europe-heatwave-2026",
    onchainMarketId: 1004,
    question:
      "[DEMO] Will Paris, Madrid, or Rome record 40°C before September 30, 2026?",
    slug: "europe-capital-heatwave-2026-demo",
    description:
      "A fictional multi-city temperature market using designated airport weather stations and a fixed observation window.",
    category: "temperature",
    continent: "Europe",
    region: "Paris–Madrid–Rome",
    latitude: 44.5,
    longitude: 5.5,
    closeTime: "2026-09-30T23:59:59.000Z",
    resolutionTime: "2026-10-10T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.58,
    noPrice: 0.42,
    yesLiquidity: 696,
    noLiquidity: 504,
    totalVolume: 4_310,
    participants: 278,
    resolutionSource:
      "WMO climate data catalogue and designated national stations",
    resolutionSourceUrl: "https://climatedata-catalogue-wmo.org/",
    resolutionRules:
      "Resolve YES if any designated station publishes an official daily maximum of at least 40.0°C before close. Corrections published within seven days control.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-10T14:00:00.000Z",
    featured: true,
    trendingScore: 94,
    history: buildHistory({
      start: "2026-05-10T00:00:00.000Z",
      yesProbabilities: [0.36, 0.39, 0.43, 0.46, 0.51, 0.55, 0.58],
      baseLiquidity: 540,
      baseVolume: 770,
      liquidityStep: 110,
      volumeStep: 590,
    }),
    evidence: buildEvidence({
      marketId: "demo-europe-heatwave-2026",
      publisher: "World Meteorological Organization",
      sourceUrl: "https://climatedata-catalogue-wmo.org/",
      sourceTitle: "WMO climate data catalogue",
      methodologyUrl:
        "https://community.wmo.int/en/activity-areas/climate-services",
      methodologyTitle: "WMO climate services overview",
      publishedAt: "2026-05-10T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-europe-heatwave-2026", [
      ["yes", 4.2, 0.58, "2026-07-18T02:02:00.000Z"],
      ["yes", 1.3, 0.56, "2026-07-17T16:48:00.000Z"],
      ["no", 2.6, 0.43, "2026-07-17T10:00:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-bangladesh-flooding-2026",
    onchainMarketId: 1005,
    question:
      "[DEMO] Will the Jamuna River cross the stated danger level before November 30, 2026?",
    slug: "bangladesh-jamuna-flooding-2026-demo",
    description:
      "A fictional sample flood-risk market tied to one named gauge and a threshold fixed in the resolution rules.",
    category: "flooding",
    continent: "Asia",
    country: "Bangladesh",
    region: "Jamuna River Basin",
    latitude: 24.75,
    longitude: 89.75,
    closeTime: "2026-11-30T23:59:59.000Z",
    resolutionTime: "2026-12-10T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.67,
    noPrice: 0.33,
    yesLiquidity: 536,
    noLiquidity: 264,
    totalVolume: 2_110,
    participants: 156,
    resolutionSource: "Bangladesh Flood Forecasting and Warning Centre",
    resolutionSourceUrl: "https://www.ffwc.gov.bd/",
    resolutionRules:
      "Resolve YES if the designated Bahadurabad gauge's official daily bulletin reports a level at or above the rule's fixed danger threshold before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-20T14:00:00.000Z",
    featured: true,
    trendingScore: 88,
    history: buildHistory({
      start: "2026-05-20T00:00:00.000Z",
      yesProbabilities: [0.49, 0.52, 0.57, 0.61, 0.64, 0.63, 0.67],
      baseLiquidity: 350,
      baseVolume: 410,
      liquidityStep: 75,
      volumeStep: 283.33,
    }),
    evidence: buildEvidence({
      marketId: "demo-bangladesh-flooding-2026",
      publisher: "Flood Forecasting and Warning Centre",
      sourceUrl: "https://www.ffwc.gov.bd/",
      sourceTitle: "Bangladesh flood warning portal",
      methodologyUrl: "https://www.ffwc.gov.bd/",
      methodologyTitle: "River monitoring and warning information",
      publishedAt: "2026-05-20T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-bangladesh-flooding-2026", [
      ["yes", 2.7, 0.67, "2026-07-17T23:20:00.000Z"],
      ["no", 0.8, 0.34, "2026-07-17T15:15:00.000Z"],
      ["yes", 1.5, 0.65, "2026-07-16T18:40:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-kenya-maize-yield-2027",
    onchainMarketId: 1006,
    question:
      "[DEMO] Will Kenya's sample maize-yield index fall below 1.8 t/ha for the 2026 season?",
    slug: "kenya-maize-yield-2026-demo",
    description:
      "A fictional agricultural risk market illustrating how a published crop report could resolve a regional hedge.",
    category: "crop-yield",
    continent: "Africa",
    country: "Kenya",
    region: "Kenyan maize-growing counties",
    latitude: 0.0236,
    longitude: 37.9062,
    closeTime: "2027-01-31T23:59:59.000Z",
    resolutionTime: "2027-03-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.38,
    noPrice: 0.62,
    yesLiquidity: 285,
    noLiquidity: 465,
    totalVolume: 1_320,
    participants: 87,
    resolutionSource:
      "Kenya National Bureau of Statistics agriculture publications",
    resolutionSourceUrl: "https://www.knbs.or.ke/",
    resolutionRules:
      "Resolve YES if the designated final national report publishes a 2026 maize yield below 1.8 metric tonnes per hectare. A preliminary estimate does not resolve the market.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-01T14:00:00.000Z",
    featured: false,
    trendingScore: 72,
    history: buildHistory({
      start: "2026-06-01T00:00:00.000Z",
      yesProbabilities: [0.46, 0.44, 0.43, 0.4, 0.41, 0.39, 0.38],
      baseLiquidity: 330,
      baseVolume: 290,
      liquidityStep: 70,
      volumeStep: 171.67,
    }),
    evidence: buildEvidence({
      marketId: "demo-kenya-maize-yield-2027",
      publisher: "Kenya National Bureau of Statistics",
      sourceUrl: "https://www.knbs.or.ke/",
      sourceTitle: "KNBS publications portal",
      methodologyUrl: "https://www.fao.org/faostat/en/#data/QCL",
      methodologyTitle: "FAOSTAT crop and livestock methodology context",
      publishedAt: "2026-06-01T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-kenya-maize-yield-2027", [
      ["no", 1.7, 0.62, "2026-07-17T18:00:00.000Z"],
      ["yes", 0.65, 0.39, "2026-07-16T13:20:00.000Z"],
      ["no", 1.1, 0.6, "2026-07-15T09:45:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-australia-wildfire-2027",
    onchainMarketId: 1007,
    question:
      "[DEMO] Will Victoria declare a Catastrophic fire-danger day before March 31, 2027?",
    slug: "victoria-catastrophic-fire-danger-2027-demo",
    description:
      "A fictional wildfire-risk market using the official Australian Fire Danger Rating System terminology.",
    category: "wildfire",
    continent: "Oceania",
    country: "Australia",
    region: "Victoria",
    latitude: -37.4713,
    longitude: 144.7852,
    closeTime: "2027-03-31T23:59:59.000Z",
    resolutionTime: "2027-04-10T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.35,
    noPrice: 0.65,
    yesLiquidity: 332.5,
    noLiquidity: 617.5,
    totalVolume: 1_870,
    participants: 132,
    resolutionSource: "Australian Bureau of Meteorology warning archive",
    resolutionSourceUrl:
      "https://www.bom.gov.au/weather-and-climate/fire-weather",
    resolutionRules:
      "Resolve YES if an official Victorian district forecast is rated Catastrophic under AFDRS before close; otherwise NO. Local unofficial reports do not count.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-10T14:00:00.000Z",
    featured: true,
    trendingScore: 83,
    history: buildHistory({
      start: "2026-06-10T00:00:00.000Z",
      yesProbabilities: [0.28, 0.3, 0.29, 0.31, 0.33, 0.34, 0.35],
      baseLiquidity: 470,
      baseVolume: 440,
      liquidityStep: 80,
      volumeStep: 238.33,
    }),
    evidence: buildEvidence({
      marketId: "demo-australia-wildfire-2027",
      publisher: "Australian Bureau of Meteorology",
      sourceUrl: "https://www.bom.gov.au/weather-and-climate/fire-weather",
      sourceTitle: "Bureau of Meteorology fire weather information",
      methodologyUrl: "https://www.afac.com.au/initiative/afdrs",
      methodologyTitle: "Australian Fire Danger Rating System",
      publishedAt: "2026-06-10T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-australia-wildfire-2027", [
      ["no", 2.2, 0.65, "2026-07-17T21:12:00.000Z"],
      ["yes", 1.4, 0.35, "2026-07-17T05:30:00.000Z"],
      ["no", 0.7, 0.64, "2026-07-16T20:05:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-amazon-dry-season-2026",
    onchainMarketId: 1008,
    question:
      "[DEMO] Was Manaus dry-season rainfall below the sample threshold by May 31, 2026?",
    slug: "manaus-dry-season-rainfall-2026-demo",
    description:
      "A resolved fictional market demonstrating settlement against a pre-defined monthly rainfall aggregation rule.",
    category: "rainfall",
    continent: "South America",
    country: "Brazil",
    region: "Manaus, Amazonas",
    latitude: -3.119,
    longitude: -60.0217,
    closeTime: "2026-05-31T23:59:59.000Z",
    resolutionTime: "2026-06-15T18:00:00.000Z",
    status: "resolved",
    outcome: "no",
    yesPrice: 0.46,
    noPrice: 0.54,
    yesLiquidity: 368,
    noLiquidity: 432,
    totalVolume: 2_540,
    participants: 143,
    resolutionSource: "INMET historical station observations",
    resolutionSourceUrl: "https://portal.inmet.gov.br/",
    resolutionRules:
      "Resolve YES if the final quality-controlled total for the designated Manaus station is below the fixed sample threshold; otherwise NO. This demo outcome is fictional.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-02-01T14:00:00.000Z",
    featured: false,
    trendingScore: 48,
    history: buildHistory({
      start: "2026-02-01T00:00:00.000Z",
      yesProbabilities: [0.55, 0.53, 0.51, 0.49, 0.47, 0.45, 0.46],
      baseLiquidity: 410,
      baseVolume: 520,
      liquidityStep: 65,
      volumeStep: 336.67,
      cadenceDays: 18,
    }),
    evidence: buildEvidence({
      marketId: "demo-amazon-dry-season-2026",
      publisher: "Instituto Nacional de Meteorologia",
      sourceUrl: "https://portal.inmet.gov.br/",
      sourceTitle: "INMET observation portal (proposed resolution source)",
      methodologyUrl: "https://portal.inmet.gov.br/",
      methodologyTitle: "INMET station information",
      publishedAt: "2026-02-01T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-amazon-dry-season-2026", [
      ["no", 3.1, 0.54, "2026-05-31T19:22:00.000Z"],
      ["yes", 1.6, 0.47, "2026-05-31T11:30:00.000Z"],
      ["no", 0.95, 0.52, "2026-05-30T22:40:00.000Z"],
    ]),
    resolution: {
      outcome: "no",
      resolvedAt: "2026-06-15T18:00:00.000Z",
      resolver: DEMO_WALLETS.cirrus,
      transactionSignature: DEMO_SIGNATURES[2],
      note: "Fictional resolver submission for demonstration; it does not assert a real observed rainfall result.",
    },
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-netherlands-coastal-flood-2026",
    onchainMarketId: 1009,
    question:
      "[DEMO] Will the sample Rotterdam water-level threshold be exceeded before August 31, 2026?",
    slug: "rotterdam-water-level-2026-demo",
    description:
      "A cancelled fictional market included to demonstrate refund behavior when the specified observation series cannot be used.",
    category: "flooding",
    continent: "Europe",
    country: "Netherlands",
    region: "Rotterdam",
    latitude: 51.9244,
    longitude: 4.4777,
    closeTime: "2026-08-31T23:59:59.000Z",
    resolutionTime: "2026-07-12T18:00:00.000Z",
    status: "cancelled",
    outcome: "cancelled",
    yesPrice: 0.29,
    noPrice: 0.71,
    yesLiquidity: 174,
    noLiquidity: 426,
    totalVolume: 980,
    participants: 61,
    resolutionSource: "Rijkswaterstaat water data portal",
    resolutionSourceUrl: "https://waterinfo.rws.nl/",
    resolutionRules:
      "Resolve from the designated gauge only. Cancel if the series is unavailable or materially revised for the required window; all contributions then become refundable.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-04-20T14:00:00.000Z",
    featured: false,
    trendingScore: 12,
    history: buildHistory({
      start: "2026-04-20T00:00:00.000Z",
      yesProbabilities: [0.37, 0.35, 0.32, 0.31, 0.3, 0.29],
      baseLiquidity: 350,
      baseVolume: 280,
      liquidityStep: 50,
      volumeStep: 140,
    }),
    evidence: buildEvidence({
      marketId: "demo-netherlands-coastal-flood-2026",
      publisher: "Rijkswaterstaat",
      sourceUrl: "https://waterinfo.rws.nl/",
      sourceTitle: "Dutch water information portal",
      methodologyUrl: "https://www.rijkswaterstaat.nl/en/water",
      methodologyTitle: "Rijkswaterstaat water management overview",
      publishedAt: "2026-04-20T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-netherlands-coastal-flood-2026", [
      ["no", 1.4, 0.71, "2026-07-11T15:22:00.000Z"],
      ["yes", 0.6, 0.29, "2026-07-10T08:10:00.000Z"],
      ["no", 0.8, 0.7, "2026-07-09T20:45:00.000Z"],
    ]),
    resolution: {
      outcome: "cancelled",
      resolvedAt: "2026-07-12T18:00:00.000Z",
      resolver: DEMO_WALLETS.cirrus,
      transactionSignature: DEMO_SIGNATURES[3],
      note: "Fictional cancellation used to demonstrate refundable positions.",
    },
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-texas-heat-2026",
    onchainMarketId: 1010,
    question:
      "[DEMO] Will any Texas station record 110°F (43.3°C) before August 5, 2026?",
    slug: "texas-extreme-heat-2026-demo",
    description:
      "A fictional sample market tracking whether a designated Texas weather station reports an official daily maximum at or above 110°F during the stated window.",
    category: "temperature",
    continent: "North America",
    country: "United States",
    region: "Texas",
    latitude: 31.0,
    longitude: -99.0,
    closeTime: "2026-08-05T23:59:59.000Z",
    resolutionTime: "2026-08-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.78,
    noPrice: 0.22,
    yesLiquidity: 936,
    noLiquidity: 264,
    totalVolume: 5_240,
    participants: 312,
    resolutionSource: "NOAA National Weather Service climate records",
    resolutionSourceUrl: "https://www.weather.gov/",
    resolutionRules:
      "Resolve YES if any designated Texas NWS station publishes an official daily maximum of at least 110°F (43.3°C) before close; otherwise NO. Corrections published within seven days control.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-05T14:00:00.000Z",
    featured: true,
    trendingScore: 90,
    history: buildHistory({
      start: "2026-05-05T00:00:00.000Z",
      yesProbabilities: [0.62, 0.66, 0.69, 0.72, 0.75, 0.77, 0.78],
      baseLiquidity: 620,
      baseVolume: 900,
      liquidityStep: 90,
      volumeStep: 620,
    }),
    evidence: buildEvidence({
      marketId: "demo-texas-heat-2026",
      publisher: "NOAA National Weather Service",
      sourceUrl: "https://www.weather.gov/",
      sourceTitle: "NWS climate records (proposed resolution source)",
      methodologyUrl: "https://www.weather.gov/climate/",
      methodologyTitle: "NWS climate normals and records overview",
      publishedAt: "2026-05-05T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-texas-heat-2026", [
      ["yes", 3.2, 0.78, "2026-07-17T18:30:00.000Z"],
      ["yes", 1.1, 0.77, "2026-07-17T09:12:00.000Z"],
      ["no", 0.9, 0.23, "2026-07-16T20:40:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-pnw-wildfire-2026",
    onchainMarketId: 1011,
    question:
      "[DEMO] Will Oregon record a 100,000+ acre wildfire before October 15, 2026?",
    slug: "pacific-northwest-wildfire-2026-demo",
    description:
      "A fictional sample market based on whether a single wildfire incident in Oregon surpasses the stated size threshold during the 2026 season.",
    category: "wildfire",
    continent: "North America",
    country: "United States",
    region: "Oregon",
    latitude: 44.0,
    longitude: -120.5,
    closeTime: "2026-10-15T23:59:59.000Z",
    resolutionTime: "2026-10-25T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.44,
    noPrice: 0.56,
    yesLiquidity: 396,
    noLiquidity: 504,
    totalVolume: 2_610,
    participants: 158,
    resolutionSource: "National Interagency Fire Center incident reports",
    resolutionSourceUrl: "https://www.nifc.gov/",
    resolutionRules:
      "Resolve YES if an official NIFC/InciWeb incident report lists an Oregon wildfire exceeding 100,000 acres before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-12T14:00:00.000Z",
    featured: false,
    trendingScore: 74,
    history: buildHistory({
      start: "2026-05-12T00:00:00.000Z",
      yesProbabilities: [0.5, 0.48, 0.46, 0.45, 0.43, 0.44, 0.44],
      baseLiquidity: 500,
      baseVolume: 600,
      liquidityStep: 57,
      volumeStep: 335,
    }),
    evidence: buildEvidence({
      marketId: "demo-pnw-wildfire-2026",
      publisher: "National Interagency Fire Center",
      sourceUrl: "https://www.nifc.gov/",
      sourceTitle: "NIFC incident reporting (proposed resolution source)",
      methodologyUrl: "https://firms.modaps.eosdis.nasa.gov/",
      methodologyTitle: "NASA FIRMS active fire methodology",
      publishedAt: "2026-05-12T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-pnw-wildfire-2026", [
      ["no", 1.6, 0.56, "2026-07-17T15:00:00.000Z"],
      ["yes", 1.2, 0.44, "2026-07-16T22:10:00.000Z"],
      ["no", 0.7, 0.55, "2026-07-16T11:05:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-argentina-drought-2026",
    onchainMarketId: 1012,
    question:
      "[DEMO] Will the Argentine Pampas enter severe drought before December 31, 2026?",
    slug: "argentina-pampas-drought-2026-demo",
    description:
      "A fictional sample market tied to whether the national meteorological service classifies core Pampas cropland at a severe-drought level during 2026.",
    category: "drought",
    continent: "South America",
    country: "Argentina",
    region: "Pampas",
    latitude: -34.6,
    longitude: -63.0,
    closeTime: "2026-12-31T23:59:59.000Z",
    resolutionTime: "2027-01-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.55,
    noPrice: 0.45,
    yesLiquidity: 550,
    noLiquidity: 450,
    totalVolume: 3_120,
    participants: 176,
    resolutionSource: "Servicio Meteorológico Nacional (Argentina)",
    resolutionSourceUrl: "https://www.smn.gob.ar/",
    resolutionRules:
      "Resolve YES if an official SMN drought bulletin classifies the core Pampas cropland region at a severe-drought level before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-18T14:00:00.000Z",
    featured: false,
    trendingScore: 69,
    history: buildHistory({
      start: "2026-05-18T00:00:00.000Z",
      yesProbabilities: [0.44, 0.47, 0.5, 0.52, 0.54, 0.53, 0.55],
      baseLiquidity: 520,
      baseVolume: 700,
      liquidityStep: 68,
      volumeStep: 402,
    }),
    evidence: buildEvidence({
      marketId: "demo-argentina-drought-2026",
      publisher: "Servicio Meteorológico Nacional",
      sourceUrl: "https://www.smn.gob.ar/",
      sourceTitle: "SMN drought monitoring (proposed resolution source)",
      methodologyUrl: "https://edo.jrc.ec.europa.eu/",
      methodologyTitle: "Copernicus drought indicator methodology",
      publishedAt: "2026-05-18T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-argentina-drought-2026", [
      ["yes", 2.1, 0.55, "2026-07-17T17:20:00.000Z"],
      ["no", 1.3, 0.46, "2026-07-17T08:40:00.000Z"],
      ["yes", 0.8, 0.53, "2026-07-16T19:15:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-peru-elnino-2027",
    onchainMarketId: 1013,
    question:
      "[DEMO] Will Peru declare a coastal El Niño before February 28, 2027?",
    slug: "peru-coastal-elnino-2027-demo",
    description:
      "A fictional sample market based on whether Peru's meteorological service declares coastal El Niño conditions with above-normal rainfall for the northern coast.",
    category: "rainfall",
    continent: "South America",
    country: "Peru",
    region: "Peruvian coast",
    latitude: -12.05,
    longitude: -77.04,
    closeTime: "2027-02-28T23:59:59.000Z",
    resolutionTime: "2027-03-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.64,
    noPrice: 0.36,
    yesLiquidity: 640,
    noLiquidity: 360,
    totalVolume: 3_480,
    participants: 205,
    resolutionSource: "SENAMHI Peru official bulletins",
    resolutionSourceUrl: "https://www.senamhi.gob.pe/",
    resolutionRules:
      "Resolve YES if SENAMHI officially declares coastal El Niño conditions with above-normal rainfall for the northern coast before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-01T14:00:00.000Z",
    featured: true,
    trendingScore: 85,
    history: buildHistory({
      start: "2026-06-01T00:00:00.000Z",
      yesProbabilities: [0.5, 0.54, 0.57, 0.6, 0.62, 0.63, 0.64],
      baseLiquidity: 560,
      baseVolume: 760,
      liquidityStep: 80,
      volumeStep: 453,
    }),
    evidence: buildEvidence({
      marketId: "demo-peru-elnino-2027",
      publisher: "SENAMHI",
      sourceUrl: "https://www.senamhi.gob.pe/",
      sourceTitle: "SENAMHI climate bulletins (proposed resolution source)",
      methodologyUrl: "https://www.weather.gov/",
      methodologyTitle: "ENSO monitoring background",
      publishedAt: "2026-06-01T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-peru-elnino-2027", [
      ["yes", 2.8, 0.64, "2026-07-17T21:30:00.000Z"],
      ["yes", 1.4, 0.62, "2026-07-17T12:00:00.000Z"],
      ["no", 1.0, 0.37, "2026-07-16T16:25:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-iberia-drought-2026",
    onchainMarketId: 1014,
    question:
      "[DEMO] Will Andalusia be in meteorological drought before November 30, 2026?",
    slug: "iberia-andalusia-drought-2026-demo",
    description:
      "A fictional sample market tracking whether Spain's meteorological agency reports meteorological drought across the Andalusia region during 2026.",
    category: "drought",
    continent: "Europe",
    country: "Spain",
    region: "Andalusia",
    latitude: 37.39,
    longitude: -5.99,
    closeTime: "2026-11-30T23:59:59.000Z",
    resolutionTime: "2026-12-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.69,
    noPrice: 0.31,
    yesLiquidity: 690,
    noLiquidity: 310,
    totalVolume: 3_020,
    participants: 187,
    resolutionSource: "Agencia Estatal de Meteorología (AEMET)",
    resolutionSourceUrl: "https://www.aemet.es/",
    resolutionRules:
      "Resolve YES if an official AEMET report classifies the Andalusia region as being in meteorological drought before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-22T14:00:00.000Z",
    featured: false,
    trendingScore: 72,
    history: buildHistory({
      start: "2026-05-22T00:00:00.000Z",
      yesProbabilities: [0.56, 0.59, 0.62, 0.64, 0.66, 0.68, 0.69],
      baseLiquidity: 560,
      baseVolume: 720,
      liquidityStep: 72,
      volumeStep: 383,
    }),
    evidence: buildEvidence({
      marketId: "demo-iberia-drought-2026",
      publisher: "Agencia Estatal de Meteorología",
      sourceUrl: "https://www.aemet.es/",
      sourceTitle: "AEMET drought reporting (proposed resolution source)",
      methodologyUrl: "https://edo.jrc.ec.europa.eu/",
      methodologyTitle: "Copernicus European Drought Observatory",
      publishedAt: "2026-05-22T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-iberia-drought-2026", [
      ["yes", 2.4, 0.69, "2026-07-17T19:05:00.000Z"],
      ["no", 0.9, 0.32, "2026-07-17T10:30:00.000Z"],
      ["yes", 1.1, 0.67, "2026-07-16T18:15:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-greece-wildfire-2026",
    onchainMarketId: 1015,
    question:
      "[DEMO] Will Attica record a 5,000+ hectare wildfire before August 14, 2026?",
    slug: "greece-attica-wildfire-2026-demo",
    description:
      "A fictional sample market based on whether the European Forest Fire Information System records a large burned-area event in the Attica region during 2026.",
    category: "wildfire",
    continent: "Europe",
    country: "Greece",
    region: "Attica",
    latitude: 37.98,
    longitude: 23.73,
    closeTime: "2026-08-14T23:59:59.000Z",
    resolutionTime: "2026-08-21T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.57,
    noPrice: 0.43,
    yesLiquidity: 570,
    noLiquidity: 430,
    totalVolume: 2_780,
    participants: 169,
    resolutionSource: "European Forest Fire Information System (EFFIS)",
    resolutionSourceUrl: "https://effis.jrc.ec.europa.eu/",
    resolutionRules:
      "Resolve YES if EFFIS records a single burned-area event exceeding 5,000 hectares in the Attica region before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-28T14:00:00.000Z",
    featured: false,
    trendingScore: 76,
    history: buildHistory({
      start: "2026-05-28T00:00:00.000Z",
      yesProbabilities: [0.46, 0.49, 0.51, 0.53, 0.55, 0.56, 0.57],
      baseLiquidity: 520,
      baseVolume: 640,
      liquidityStep: 66,
      volumeStep: 356,
    }),
    evidence: buildEvidence({
      marketId: "demo-greece-wildfire-2026",
      publisher: "Copernicus EFFIS",
      sourceUrl: "https://effis.jrc.ec.europa.eu/",
      sourceTitle: "EFFIS burned-area reporting (proposed resolution source)",
      methodologyUrl: "https://firms.modaps.eosdis.nasa.gov/",
      methodologyTitle: "NASA FIRMS active fire methodology",
      publishedAt: "2026-05-28T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-greece-wildfire-2026", [
      ["yes", 1.9, 0.57, "2026-07-17T20:10:00.000Z"],
      ["no", 1.2, 0.44, "2026-07-17T11:45:00.000Z"],
      ["yes", 0.8, 0.55, "2026-07-16T17:30:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-sahel-drought-2026",
    onchainMarketId: 1016,
    question:
      "[DEMO] Will the western Sahel reach IPC Crisis levels before November 30, 2026?",
    slug: "sahel-niger-drought-2026-demo",
    description:
      "A fictional sample market tied to whether an early-warning assessment classifies the western Sahel at a drought-driven food-security crisis level during 2026.",
    category: "drought",
    continent: "Africa",
    country: "Niger",
    region: "Western Sahel",
    latitude: 13.51,
    longitude: 2.11,
    closeTime: "2026-11-30T23:59:59.000Z",
    resolutionTime: "2026-12-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.74,
    noPrice: 0.26,
    yesLiquidity: 740,
    noLiquidity: 260,
    totalVolume: 2_940,
    participants: 178,
    resolutionSource: "Famine Early Warning Systems Network (FEWS NET)",
    resolutionSourceUrl: "https://fews.net/",
    resolutionRules:
      "Resolve YES if a FEWS NET assessment classifies the western Sahel at Crisis (IPC Phase 3) primarily driven by drought before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-03T14:00:00.000Z",
    featured: false,
    trendingScore: 70,
    history: buildHistory({
      start: "2026-06-03T00:00:00.000Z",
      yesProbabilities: [0.6, 0.64, 0.67, 0.7, 0.72, 0.73, 0.74],
      baseLiquidity: 540,
      baseVolume: 660,
      liquidityStep: 74,
      volumeStep: 380,
    }),
    evidence: buildEvidence({
      marketId: "demo-sahel-drought-2026",
      publisher: "FEWS NET",
      sourceUrl: "https://fews.net/",
      sourceTitle: "FEWS NET food-security assessment (proposed source)",
      methodologyUrl: "https://www.ipcinfo.org/",
      methodologyTitle: "IPC acute food insecurity classification",
      publishedAt: "2026-06-03T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-sahel-drought-2026", [
      ["yes", 2.6, 0.74, "2026-07-17T22:40:00.000Z"],
      ["yes", 1.0, 0.72, "2026-07-17T13:20:00.000Z"],
      ["no", 0.6, 0.27, "2026-07-16T15:50:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-horn-africa-drought-2027",
    onchainMarketId: 1017,
    question:
      "[DEMO] Will the Horn of Africa see a below-average rainy season by January 31, 2027?",
    slug: "horn-of-africa-drought-2027-demo",
    description:
      "A fictional sample market based on whether a regional climate assessment reports a below-average rainy season and drought for the Horn of Africa.",
    category: "drought",
    continent: "Africa",
    country: "Ethiopia",
    region: "Horn of Africa",
    latitude: 9.15,
    longitude: 40.49,
    closeTime: "2027-01-31T23:59:59.000Z",
    resolutionTime: "2027-02-15T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.82,
    noPrice: 0.18,
    yesLiquidity: 820,
    noLiquidity: 180,
    totalVolume: 3_360,
    participants: 214,
    resolutionSource: "IGAD Climate Prediction and Applications Centre (ICPAC)",
    resolutionSourceUrl: "https://www.icpac.net/",
    resolutionRules:
      "Resolve YES if an official ICPAC seasonal assessment reports below-average rainfall constituting drought for the Horn of Africa before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-05T14:00:00.000Z",
    featured: true,
    trendingScore: 88,
    history: buildHistory({
      start: "2026-06-05T00:00:00.000Z",
      yesProbabilities: [0.68, 0.72, 0.75, 0.78, 0.8, 0.81, 0.82],
      baseLiquidity: 560,
      baseVolume: 720,
      liquidityStep: 86,
      volumeStep: 440,
    }),
    evidence: buildEvidence({
      marketId: "demo-horn-africa-drought-2027",
      publisher: "ICPAC",
      sourceUrl: "https://www.icpac.net/",
      sourceTitle: "ICPAC seasonal assessment (proposed resolution source)",
      methodologyUrl: "https://fews.net/",
      methodologyTitle: "Regional food-security and climate outlook",
      publishedAt: "2026-06-05T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-horn-africa-drought-2027", [
      ["yes", 3.4, 0.82, "2026-07-18T00:20:00.000Z"],
      ["yes", 1.7, 0.8, "2026-07-17T14:35:00.000Z"],
      ["no", 0.7, 0.19, "2026-07-16T21:10:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-capetown-water-2027",
    onchainMarketId: 1018,
    question:
      "[DEMO] Will Cape Town dam levels fall below 30% before March 31, 2027?",
    slug: "cape-town-dam-levels-2027-demo",
    description:
      "A fictional sample market tracking whether combined municipal dam storage for Cape Town drops beneath the stated threshold during the window.",
    category: "drought",
    continent: "Africa",
    country: "South Africa",
    region: "Western Cape",
    latitude: -33.92,
    longitude: 18.42,
    closeTime: "2027-03-31T23:59:59.000Z",
    resolutionTime: "2027-04-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.33,
    noPrice: 0.67,
    yesLiquidity: 330,
    noLiquidity: 670,
    totalVolume: 2_050,
    participants: 141,
    resolutionSource: "South African Weather Service and City of Cape Town",
    resolutionSourceUrl: "https://www.weathersa.co.za/",
    resolutionRules:
      "Resolve YES if the City of Cape Town's official combined dam-level report falls below 30% on any weekly release before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-08T14:00:00.000Z",
    featured: false,
    trendingScore: 58,
    history: buildHistory({
      start: "2026-06-08T00:00:00.000Z",
      yesProbabilities: [0.42, 0.4, 0.38, 0.36, 0.35, 0.34, 0.33],
      baseLiquidity: 500,
      baseVolume: 520,
      liquidityStep: 60,
      volumeStep: 305,
    }),
    evidence: buildEvidence({
      marketId: "demo-capetown-water-2027",
      publisher: "South African Weather Service",
      sourceUrl: "https://www.weathersa.co.za/",
      sourceTitle: "Dam-level reporting (proposed resolution source)",
      methodologyUrl: "https://edo.jrc.ec.europa.eu/",
      methodologyTitle: "Drought indicator methodology background",
      publishedAt: "2026-06-08T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-capetown-water-2027", [
      ["no", 2.0, 0.67, "2026-07-17T18:55:00.000Z"],
      ["yes", 0.8, 0.33, "2026-07-16T23:05:00.000Z"],
      ["no", 1.1, 0.66, "2026-07-16T09:40:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-india-monsoon-2026",
    onchainMarketId: 1019,
    question:
      "[DEMO] Will Maharashtra record above-normal monsoon rainfall by September 30, 2026?",
    slug: "india-maharashtra-monsoon-2026-demo",
    description:
      "A fictional sample market based on whether India's meteorological department reports above-normal seasonal monsoon rainfall for Maharashtra.",
    category: "rainfall",
    continent: "Asia",
    country: "India",
    region: "Maharashtra",
    latitude: 19.08,
    longitude: 72.88,
    closeTime: "2026-09-30T23:59:59.000Z",
    resolutionTime: "2026-10-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.66,
    noPrice: 0.34,
    yesLiquidity: 660,
    noLiquidity: 340,
    totalVolume: 3_610,
    participants: 233,
    resolutionSource: "India Meteorological Department (IMD)",
    resolutionSourceUrl: "https://mausam.imd.gov.in/",
    resolutionRules:
      "Resolve YES if the IMD end-of-season report classifies Maharashtra's monsoon rainfall as above normal before close; otherwise NO. Preliminary figures do not resolve the market.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-05-30T14:00:00.000Z",
    featured: true,
    trendingScore: 87,
    history: buildHistory({
      start: "2026-05-30T00:00:00.000Z",
      yesProbabilities: [0.54, 0.57, 0.6, 0.62, 0.64, 0.65, 0.66],
      baseLiquidity: 560,
      baseVolume: 780,
      liquidityStep: 76,
      volumeStep: 470,
    }),
    evidence: buildEvidence({
      marketId: "demo-india-monsoon-2026",
      publisher: "India Meteorological Department",
      sourceUrl: "https://mausam.imd.gov.in/",
      sourceTitle: "IMD monsoon reporting (proposed resolution source)",
      methodologyUrl: "https://mausam.imd.gov.in/",
      methodologyTitle: "IMD seasonal rainfall classification",
      publishedAt: "2026-05-30T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-india-monsoon-2026", [
      ["yes", 2.9, 0.66, "2026-07-17T23:50:00.000Z"],
      ["yes", 1.5, 0.64, "2026-07-17T15:30:00.000Z"],
      ["no", 1.0, 0.35, "2026-07-16T18:20:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-japan-typhoon-2026",
    onchainMarketId: 1020,
    question:
      "[DEMO] Will a typhoon make landfall on Honshu before October 31, 2026?",
    slug: "japan-honshu-typhoon-2026-demo",
    description:
      "A fictional sample market tied to whether Japan's meteorological agency records a typhoon making landfall on the island of Honshu during the season.",
    category: "hurricane",
    continent: "Asia",
    country: "Japan",
    region: "Kanto, Honshu",
    latitude: 35.68,
    longitude: 139.69,
    closeTime: "2026-10-31T23:59:59.000Z",
    resolutionTime: "2026-11-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.59,
    noPrice: 0.41,
    yesLiquidity: 590,
    noLiquidity: 410,
    totalVolume: 3_240,
    participants: 198,
    resolutionSource: "Japan Meteorological Agency (JMA)",
    resolutionSourceUrl: "https://www.jma.go.jp/",
    resolutionRules:
      "Resolve YES if an official JMA record identifies a typhoon making landfall on Honshu before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-10T14:00:00.000Z",
    featured: false,
    trendingScore: 79,
    history: buildHistory({
      start: "2026-06-10T00:00:00.000Z",
      yesProbabilities: [0.48, 0.51, 0.54, 0.56, 0.57, 0.58, 0.59],
      baseLiquidity: 540,
      baseVolume: 700,
      liquidityStep: 70,
      volumeStep: 423,
    }),
    evidence: buildEvidence({
      marketId: "demo-japan-typhoon-2026",
      publisher: "Japan Meteorological Agency",
      sourceUrl: "https://www.jma.go.jp/",
      sourceTitle: "JMA typhoon records (proposed resolution source)",
      methodologyUrl: "https://www.jma.go.jp/jma/en/Activities/typhoon.html",
      methodologyTitle: "JMA tropical cyclone information",
      publishedAt: "2026-06-10T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-japan-typhoon-2026", [
      ["yes", 2.2, 0.59, "2026-07-17T19:40:00.000Z"],
      ["no", 1.3, 0.42, "2026-07-17T10:15:00.000Z"],
      ["yes", 0.9, 0.57, "2026-07-16T20:30:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-yangtze-flooding-2026",
    onchainMarketId: 1021,
    question:
      "[DEMO] Will the middle Yangtze exceed its warning level before August 9, 2026?",
    slug: "china-yangtze-flooding-2026-demo",
    description:
      "A fictional sample flood-risk market tied to a designated Yangtze River gauge and an official warning-level threshold fixed in the rules.",
    category: "flooding",
    continent: "Asia",
    country: "China",
    region: "Middle Yangtze",
    latitude: 30.59,
    longitude: 114.3,
    closeTime: "2026-08-09T23:59:59.000Z",
    resolutionTime: "2026-08-16T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.48,
    noPrice: 0.52,
    yesLiquidity: 480,
    noLiquidity: 520,
    totalVolume: 2_460,
    participants: 162,
    resolutionSource: "China Ministry of Water Resources bulletins",
    resolutionSourceUrl: "http://www.mwr.gov.cn/",
    resolutionRules:
      "Resolve YES if the designated Hankou gauge's official bulletin reports a level at or above its published warning level before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-12T14:00:00.000Z",
    featured: false,
    trendingScore: 71,
    history: buildHistory({
      start: "2026-06-12T00:00:00.000Z",
      yesProbabilities: [0.42, 0.44, 0.46, 0.47, 0.48, 0.47, 0.48],
      baseLiquidity: 500,
      baseVolume: 560,
      liquidityStep: 62,
      volumeStep: 316,
    }),
    evidence: buildEvidence({
      marketId: "demo-yangtze-flooding-2026",
      publisher: "China Ministry of Water Resources",
      sourceUrl: "http://www.mwr.gov.cn/",
      sourceTitle: "River gauge bulletins (proposed resolution source)",
      methodologyUrl: "https://www.gdacs.org/",
      methodologyTitle: "GDACS flood monitoring background",
      publishedAt: "2026-06-12T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-yangtze-flooding-2026", [
      ["no", 1.7, 0.52, "2026-07-17T16:45:00.000Z"],
      ["yes", 1.1, 0.48, "2026-07-16T21:55:00.000Z"],
      ["no", 0.8, 0.51, "2026-07-16T12:10:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-philippines-typhoon-2026",
    onchainMarketId: 1022,
    question:
      "[DEMO] Will a Signal No. 3+ typhoon hit Luzon before December 31, 2026?",
    slug: "philippines-luzon-typhoon-2026-demo",
    description:
      "A fictional sample market based on whether the Philippine weather agency raises a high tropical-cyclone warning signal over Luzon during the season.",
    category: "hurricane",
    continent: "Asia",
    country: "Philippines",
    region: "Luzon",
    latitude: 14.6,
    longitude: 120.98,
    closeTime: "2026-12-31T23:59:59.000Z",
    resolutionTime: "2027-01-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.86,
    noPrice: 0.14,
    yesLiquidity: 860,
    noLiquidity: 140,
    totalVolume: 3_820,
    participants: 247,
    resolutionSource: "PAGASA official tropical cyclone warnings",
    resolutionSourceUrl: "https://www.pagasa.dost.gov.ph/",
    resolutionRules:
      "Resolve YES if PAGASA raises Tropical Cyclone Wind Signal No. 3 or higher over any part of Luzon before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-14T14:00:00.000Z",
    featured: true,
    trendingScore: 92,
    history: buildHistory({
      start: "2026-06-14T00:00:00.000Z",
      yesProbabilities: [0.74, 0.77, 0.8, 0.82, 0.84, 0.85, 0.86],
      baseLiquidity: 560,
      baseVolume: 800,
      liquidityStep: 90,
      volumeStep: 503,
    }),
    evidence: buildEvidence({
      marketId: "demo-philippines-typhoon-2026",
      publisher: "PAGASA",
      sourceUrl: "https://www.pagasa.dost.gov.ph/",
      sourceTitle: "PAGASA cyclone warnings (proposed resolution source)",
      methodologyUrl: "https://www.pagasa.dost.gov.ph/learning-tools",
      methodologyTitle: "Tropical cyclone wind signal system",
      publishedAt: "2026-06-14T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-philippines-typhoon-2026", [
      ["yes", 3.6, 0.86, "2026-07-18T01:35:00.000Z"],
      ["yes", 1.8, 0.84, "2026-07-17T16:10:00.000Z"],
      ["no", 0.5, 0.15, "2026-07-16T19:25:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-queensland-cyclone-2027",
    onchainMarketId: 1023,
    question:
      "[DEMO] Will a tropical cyclone cross the Queensland coast before March 31, 2027?",
    slug: "queensland-cyclone-2027-demo",
    description:
      "A fictional sample market tied to whether Australia's Bureau of Meteorology records a tropical cyclone crossing the Queensland coast during the season.",
    category: "hurricane",
    continent: "Oceania",
    country: "Australia",
    region: "Queensland",
    latitude: -19.26,
    longitude: 146.82,
    closeTime: "2027-03-31T23:59:59.000Z",
    resolutionTime: "2027-04-12T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.62,
    noPrice: 0.38,
    yesLiquidity: 620,
    noLiquidity: 380,
    totalVolume: 2_720,
    participants: 173,
    resolutionSource: "Australian Bureau of Meteorology cyclone archive",
    resolutionSourceUrl: "http://www.bom.gov.au/cyclone/",
    resolutionRules:
      "Resolve YES if an official Bureau of Meteorology record identifies a tropical cyclone crossing the Queensland coast before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-16T14:00:00.000Z",
    featured: false,
    trendingScore: 78,
    history: buildHistory({
      start: "2026-06-16T00:00:00.000Z",
      yesProbabilities: [0.52, 0.55, 0.57, 0.59, 0.6, 0.61, 0.62],
      baseLiquidity: 520,
      baseVolume: 620,
      liquidityStep: 72,
      volumeStep: 350,
    }),
    evidence: buildEvidence({
      marketId: "demo-queensland-cyclone-2027",
      publisher: "Australian Bureau of Meteorology",
      sourceUrl: "http://www.bom.gov.au/cyclone/",
      sourceTitle: "BoM cyclone archive (proposed resolution source)",
      methodologyUrl: "http://www.bom.gov.au/cyclone/about/",
      methodologyTitle: "Australian tropical cyclone intensity scale",
      publishedAt: "2026-06-16T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-queensland-cyclone-2027", [
      ["yes", 2.0, 0.62, "2026-07-17T20:50:00.000Z"],
      ["no", 1.2, 0.39, "2026-07-17T09:35:00.000Z"],
      ["yes", 0.9, 0.6, "2026-07-16T18:05:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
  {
    id: "demo-newzealand-heat-2027",
    onchainMarketId: 1024,
    question:
      "[DEMO] Will a Wellington-area station record 35°C before February 28, 2027?",
    slug: "new-zealand-wellington-heat-2027-demo",
    description:
      "A fictional sample market based on whether a designated Wellington-area station reports an official daily maximum at or above 35°C during the window.",
    category: "temperature",
    continent: "Oceania",
    country: "New Zealand",
    region: "Wellington",
    latitude: -41.29,
    longitude: 174.78,
    closeTime: "2027-02-28T23:59:59.000Z",
    resolutionTime: "2027-03-10T18:00:00.000Z",
    status: "open",
    outcome: "unresolved",
    yesPrice: 0.37,
    noPrice: 0.63,
    yesLiquidity: 370,
    noLiquidity: 630,
    totalVolume: 1_780,
    participants: 118,
    resolutionSource: "NIWA and MetService New Zealand",
    resolutionSourceUrl: "https://niwa.co.nz/",
    resolutionRules:
      "Resolve YES if a designated Wellington-area station publishes an official daily maximum of at least 35.0°C before close; otherwise NO.",
    resolver: DEMO_WALLETS.cirrus,
    createdAt: "2026-06-18T14:00:00.000Z",
    featured: false,
    trendingScore: 52,
    history: buildHistory({
      start: "2026-06-18T00:00:00.000Z",
      yesProbabilities: [0.45, 0.43, 0.41, 0.4, 0.38, 0.38, 0.37],
      baseLiquidity: 500,
      baseVolume: 460,
      liquidityStep: 58,
      volumeStep: 268,
    }),
    evidence: buildEvidence({
      marketId: "demo-newzealand-heat-2027",
      publisher: "NIWA",
      sourceUrl: "https://niwa.co.nz/",
      sourceTitle: "NIWA climate records (proposed resolution source)",
      methodologyUrl: "https://niwa.co.nz/climate",
      methodologyTitle: "New Zealand climate monitoring overview",
      publishedAt: "2026-06-18T00:00:00.000Z",
    }),
    recentTrades: buildTrades("demo-newzealand-heat-2027", [
      ["no", 1.8, 0.63, "2026-07-17T17:15:00.000Z"],
      ["yes", 0.7, 0.37, "2026-07-16T22:45:00.000Z"],
      ["no", 1.0, 0.62, "2026-07-16T10:20:00.000Z"],
    ]),
    network: "devnet",
    settlementAsset: "SOL",
    marketModel: "pooled-binary",
    isDemo: true,
    dataLabel: "SAMPLE DATA",
    dataDisclaimer: DEMO_DATA_DISCLAIMER,
  },
]

export const demoUserPositions: UserPosition[] = [
  {
    id: "demo-position-atlas-fl-yes",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-fl-hurricane-2026",
    onchainMarketId: 1001,
    marketQuestion: demoMarkets[0]!.question,
    side: "yes",
    amountLamports: "2400000000",
    amountSol: 2.4,
    estimatedPayoutLamports: "5581395348",
    estimatedPayoutSol: 5.5814,
    claimableLamports: "0",
    claimableSol: 0,
    claimedLamports: "0",
    claimedSol: 0,
    status: "open",
    marketStatus: "open",
    marketOutcome: "unresolved",
    openedAt: "2026-07-17T16:20:00.000Z",
    updatedAt: "2026-07-17T16:20:00.000Z",
    transactionSignature: DEMO_SIGNATURES[0],
    network: "devnet",
    isDemo: true,
  },
  {
    id: "demo-position-atlas-amazon-no",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-amazon-dry-season-2026",
    onchainMarketId: 1008,
    marketQuestion: demoMarkets[7]!.question,
    side: "no",
    amountLamports: "3100000000",
    amountSol: 3.1,
    estimatedPayoutLamports: "5740740740",
    estimatedPayoutSol: 5.7407,
    claimableLamports: "5740740740",
    claimableSol: 5.7407,
    claimedLamports: "0",
    claimedSol: 0,
    status: "claimable",
    marketStatus: "resolved",
    marketOutcome: "no",
    openedAt: "2026-05-31T19:22:00.000Z",
    updatedAt: "2026-06-15T18:00:00.000Z",
    transactionSignature: DEMO_SIGNATURES[1],
    network: "devnet",
    isDemo: true,
  },
  {
    id: "demo-position-atlas-rotterdam-yes",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-netherlands-coastal-flood-2026",
    onchainMarketId: 1009,
    marketQuestion: demoMarkets[8]!.question,
    side: "yes",
    amountLamports: "600000000",
    amountSol: 0.6,
    estimatedPayoutLamports: "2068965517",
    estimatedPayoutSol: 2.069,
    claimableLamports: "600000000",
    claimableSol: 0.6,
    claimedLamports: "0",
    claimedSol: 0,
    status: "refundable",
    marketStatus: "cancelled",
    marketOutcome: "cancelled",
    openedAt: "2026-07-10T08:10:00.000Z",
    updatedAt: "2026-07-12T18:00:00.000Z",
    transactionSignature: DEMO_SIGNATURES[2],
    network: "devnet",
    isDemo: true,
  },
  {
    id: "demo-position-boreal-amazon-yes",
    wallet: DEMO_WALLETS.boreal,
    marketId: "demo-amazon-dry-season-2026",
    onchainMarketId: 1008,
    marketQuestion: demoMarkets[7]!.question,
    side: "yes",
    amountLamports: "1600000000",
    amountSol: 1.6,
    estimatedPayoutLamports: "3478260869",
    estimatedPayoutSol: 3.4783,
    claimableLamports: "0",
    claimableSol: 0,
    claimedLamports: "0",
    claimedSol: 0,
    status: "lost",
    marketStatus: "resolved",
    marketOutcome: "no",
    openedAt: "2026-05-31T11:30:00.000Z",
    updatedAt: "2026-06-15T18:00:00.000Z",
    transactionSignature: DEMO_SIGNATURES[3],
    network: "devnet",
    isDemo: true,
  },
]

export const demoUserActivity: UserActivity[] = [
  {
    id: "demo-activity-atlas-fl-buy",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-fl-hurricane-2026",
    onchainMarketId: 1001,
    type: "purchase_yes",
    status: "confirmed",
    side: "yes",
    amountLamports: "2400000000",
    amountSol: 2.4,
    transactionSignature: DEMO_SIGNATURES[0],
    explorerUrl: `https://explorer.solana.com/tx/${DEMO_SIGNATURES[0]}?cluster=devnet`,
    timestamp: "2026-07-17T16:20:00.000Z",
    network: "devnet",
    isDemo: true,
  },
  {
    id: "demo-activity-atlas-amazon-buy",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-amazon-dry-season-2026",
    onchainMarketId: 1008,
    type: "purchase_no",
    status: "confirmed",
    side: "no",
    amountLamports: "3100000000",
    amountSol: 3.1,
    transactionSignature: DEMO_SIGNATURES[1],
    explorerUrl: `https://explorer.solana.com/tx/${DEMO_SIGNATURES[1]}?cluster=devnet`,
    timestamp: "2026-05-31T19:22:00.000Z",
    network: "devnet",
    isDemo: true,
  },
  {
    id: "demo-activity-atlas-rotterdam-buy",
    wallet: DEMO_WALLETS.atlas,
    marketId: "demo-netherlands-coastal-flood-2026",
    onchainMarketId: 1009,
    type: "purchase_yes",
    status: "confirmed",
    side: "yes",
    amountLamports: "600000000",
    amountSol: 0.6,
    transactionSignature: DEMO_SIGNATURES[2],
    explorerUrl: `https://explorer.solana.com/tx/${DEMO_SIGNATURES[2]}?cluster=devnet`,
    timestamp: "2026-07-10T08:10:00.000Z",
    network: "devnet",
    isDemo: true,
  },
]
