import { MongoClient } from "mongodb"
import { readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { createHash } from "node:crypto"

const __dirname = dirname(fileURLToPath(import.meta.url))

function loadEnv() {
  const content = readFileSync(resolve(__dirname, "..", ".env"), "utf-8")
  const env = {}
  for (const line of content.split("\n")) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith("#")) continue
    const eq = trimmed.indexOf("=")
    if (eq === -1) continue
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim()
  }
  return env
}

const markets = [
  { id:"demo-fl-hurricane-2026",onchainMarketId:1001,question:"[DEMO] Will Florida record a Category 4+ hurricane landfall before October 31, 2026?",slug:"florida-category-4-hurricane-2026-demo",description:"A fictional sample market tracking whether a hurricane classified as Category 4 or higher makes landfall in Florida.",category:"hurricane",continent:"North America",country:"United States",region:"Florida",latitude:27.6648,longitude:-81.5158,closeTime:"2026-10-31T23:59:59.000Z",resolutionTime:"2026-11-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.43,noPrice:0.57,yesLiquidity:430,noLiquidity:570,totalVolume:2840,participants:184,resolutionSource:"NOAA National Hurricane Center archive",resolutionSourceUrl:"https://www.nhc.noaa.gov/data/",resolutionRules:"Resolve YES if NOAA post-season archive identifies a Category 4 or 5 hurricane landfall within Florida before the close time; otherwise resolve NO.",createdAt:"2026-05-01T14:00:00.000Z",featured:true,trendingScore:96},
  { id:"demo-ca-drought-2026",onchainMarketId:1002,question:"[DEMO] Will California enter severe drought conditions before December 31, 2026?",slug:"california-severe-drought-2026-demo",description:"A fictional sample market based on whether a defined share of California reaches the severe-drought threshold during 2026.",category:"drought",continent:"North America",country:"United States",region:"California",latitude:36.7783,longitude:-119.4179,closeTime:"2026-12-31T23:59:59.000Z",resolutionTime:"2027-01-14T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.62,noPrice:0.38,yesLiquidity:775,noLiquidity:475,totalVolume:3920,participants:241,resolutionSource:"U.S. Drought Monitor California archive",resolutionSourceUrl:"https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?CA",resolutionRules:"Resolve YES if at least 25% of California is in D2 (Severe Drought) or worse on any release before close; otherwise NO.",createdAt:"2026-04-15T14:00:00.000Z",featured:true,trendingScore:91},
  { id:"demo-ontario-rainfall-june-2026",onchainMarketId:1003,question:"[DEMO] Did southern Ontario rainfall exceed its June historical average in 2026?",slug:"southern-ontario-june-rainfall-2026-demo",description:"A closed fictional sample market awaiting its authorized resolver's comparison of a designated regional rainfall index.",category:"rainfall",continent:"North America",country:"Canada",region:"Southern Ontario",latitude:43.6532,longitude:-79.3832,closeTime:"2026-06-30T23:59:59.000Z",resolutionTime:"2026-07-25T18:00:00.000Z",status:"closed",outcome:"unresolved",yesPrice:0.54,noPrice:0.46,yesLiquidity:378,noLiquidity:322,totalVolume:1680,participants:109,resolutionSource:"Environment and Climate Change Canada climate data",resolutionSourceUrl:"https://climate.weather.gc.ca/",resolutionRules:"Resolve YES if the arithmetic mean of June precipitation at the five listed reference stations exceeds the published 1991-2020 normal; otherwise NO.",createdAt:"2026-03-15T14:00:00.000Z",featured:false,trendingScore:67},
  { id:"demo-europe-heatwave-2026",onchainMarketId:1004,question:"[DEMO] Will Paris, Madrid, or Rome record 40\u00B0C before September 30, 2026?",slug:"europe-capital-heatwave-2026-demo",description:"A fictional multi-city temperature market using designated airport weather stations.",category:"temperature",continent:"Europe",region:"Paris\u2013Madrid\u2013Rome",latitude:44.5,longitude:5.5,closeTime:"2026-09-30T23:59:59.000Z",resolutionTime:"2026-10-10T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.58,noPrice:0.42,yesLiquidity:696,noLiquidity:504,totalVolume:4310,participants:278,resolutionSource:"WMO climate data catalogue",resolutionSourceUrl:"https://climatedata-catalogue-wmo.org/",resolutionRules:"Resolve YES if any designated station publishes an official daily maximum of at least 40.0\u00B0C before close.",createdAt:"2026-05-10T14:00:00.000Z",featured:true,trendingScore:94},
  { id:"demo-bangladesh-flooding-2026",onchainMarketId:1005,question:"[DEMO] Will the Jamuna River cross the stated danger level before November 30, 2026?",slug:"bangladesh-jamuna-flooding-2026-demo",description:"A fictional sample flood-risk market tied to one named gauge and a threshold fixed in the resolution rules.",category:"flooding",continent:"Asia",country:"Bangladesh",region:"Jamuna River Basin",latitude:24.75,longitude:89.75,closeTime:"2026-11-30T23:59:59.000Z",resolutionTime:"2026-12-10T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.67,noPrice:0.33,yesLiquidity:536,noLiquidity:264,totalVolume:2110,participants:156,resolutionSource:"Bangladesh Flood Forecasting and Warning Centre",resolutionSourceUrl:"https://www.ffwc.gov.bd/",resolutionRules:"Resolve YES if the designated Bahadurabad gauge reports a level at or above the danger threshold before close; otherwise NO.",createdAt:"2026-05-20T14:00:00.000Z",featured:true,trendingScore:88},
  { id:"demo-kenya-maize-yield-2027",onchainMarketId:1006,question:"[DEMO] Will Kenya's sample maize-yield index fall below 1.8 t/ha for the 2026 season?",slug:"kenya-maize-yield-2026-demo",description:"A fictional agricultural risk market illustrating how a published crop report could resolve a regional hedge.",category:"crop-yield",continent:"Africa",country:"Kenya",region:"Kenyan maize-growing counties",latitude:0.0236,longitude:37.9062,closeTime:"2027-01-31T23:59:59.000Z",resolutionTime:"2027-03-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.38,noPrice:0.62,yesLiquidity:285,noLiquidity:465,totalVolume:1320,participants:87,resolutionSource:"Kenya National Bureau of Statistics",resolutionSourceUrl:"https://www.knbs.or.ke/",resolutionRules:"Resolve YES if the designated final national report publishes a 2026 maize yield below 1.8 metric tonnes per hectare.",createdAt:"2026-06-01T14:00:00.000Z",featured:false,trendingScore:72},
  { id:"demo-australia-wildfire-2027",onchainMarketId:1007,question:"[DEMO] Will Victoria declare a Catastrophic fire-danger day before March 31, 2027?",slug:"victoria-catastrophic-fire-danger-2027-demo",description:"A fictional wildfire-risk market using the official Australian Fire Danger Rating System terminology.",category:"wildfire",continent:"Oceania",country:"Australia",region:"Victoria",latitude:-37.4713,longitude:144.7852,closeTime:"2027-03-31T23:59:59.000Z",resolutionTime:"2027-04-10T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.35,noPrice:0.65,yesLiquidity:332.5,noLiquidity:617.5,totalVolume:1870,participants:132,resolutionSource:"Australian Bureau of Meteorology warning archive",resolutionSourceUrl:"https://www.bom.gov.au/weather-and-climate/fire-weather",resolutionRules:"Resolve YES if an official Victorian district forecast is rated Catastrophic under AFDRS before close; otherwise NO.",createdAt:"2026-06-10T14:00:00.000Z",featured:true,trendingScore:83},
  { id:"demo-amazon-dry-season-2026",onchainMarketId:1008,question:"[DEMO] Was Manaus dry-season rainfall below the sample threshold by May 31, 2026?",slug:"manaus-dry-season-rainfall-2026-demo",description:"A resolved fictional market demonstrating settlement against a pre-defined monthly rainfall aggregation rule.",category:"rainfall",continent:"South America",country:"Brazil",region:"Manaus, Amazonas",latitude:-3.119,longitude:-60.0217,closeTime:"2026-05-31T23:59:59.000Z",resolutionTime:"2026-06-15T18:00:00.000Z",status:"resolved",outcome:"no",yesPrice:0.46,noPrice:0.54,yesLiquidity:368,noLiquidity:432,totalVolume:2540,participants:143,resolutionSource:"INMET historical station observations",resolutionSourceUrl:"https://portal.inmet.gov.br/",resolutionRules:"Resolve YES if the final quality-controlled total for the designated Manaus station is below the fixed sample threshold; otherwise NO.",createdAt:"2026-02-01T14:00:00.000Z",featured:false,trendingScore:48},
  { id:"demo-netherlands-coastal-flood-2026",onchainMarketId:1009,question:"[DEMO] Will the sample Rotterdam water-level threshold be exceeded before August 31, 2026?",slug:"rotterdam-water-level-2026-demo",description:"A cancelled fictional market included to demonstrate refund behavior.",category:"flooding",continent:"Europe",country:"Netherlands",region:"Rotterdam",latitude:51.9244,longitude:4.4777,closeTime:"2026-08-31T23:59:59.000Z",resolutionTime:"2026-07-12T18:00:00.000Z",status:"cancelled",outcome:"cancelled",yesPrice:0.29,noPrice:0.71,yesLiquidity:174,noLiquidity:426,totalVolume:980,participants:61,resolutionSource:"Rijkswaterstaat water data portal",resolutionSourceUrl:"https://waterinfo.rws.nl/",resolutionRules:"Resolve from the designated gauge only. Cancel if the series is unavailable or materially revised.",createdAt:"2026-04-20T14:00:00.000Z",featured:false,trendingScore:12},
  { id:"demo-texas-heat-2026",onchainMarketId:1010,question:"[DEMO] Will any Texas station record 110\u00B0F (43.3\u00B0C) before August 5, 2026?",slug:"texas-extreme-heat-2026-demo",description:"A fictional sample market tracking whether a designated Texas weather station reports an official daily maximum at or above 110\u00B0F.",category:"temperature",continent:"North America",country:"United States",region:"Texas",latitude:31.0,longitude:-99.0,closeTime:"2026-08-05T23:59:59.000Z",resolutionTime:"2026-08-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.78,noPrice:0.22,yesLiquidity:936,noLiquidity:264,totalVolume:5240,participants:312,resolutionSource:"NOAA National Weather Service climate records",resolutionSourceUrl:"https://www.weather.gov/",resolutionRules:"Resolve YES if any designated Texas NWS station publishes an official daily maximum of at least 110\u00B0F before close; otherwise NO.",createdAt:"2026-05-05T14:00:00.000Z",featured:true,trendingScore:90},
  { id:"demo-pnw-wildfire-2026",onchainMarketId:1011,question:"[DEMO] Will Oregon record a 100,000+ acre wildfire before October 15, 2026?",slug:"pacific-northwest-wildfire-2026-demo",description:"A fictional sample market based on whether a single wildfire incident in Oregon surpasses the stated size threshold.",category:"wildfire",continent:"North America",country:"United States",region:"Oregon",latitude:44.0,longitude:-120.5,closeTime:"2026-10-15T23:59:59.000Z",resolutionTime:"2026-10-25T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.44,noPrice:0.56,yesLiquidity:396,noLiquidity:504,totalVolume:2610,participants:158,resolutionSource:"National Interagency Fire Center incident reports",resolutionSourceUrl:"https://www.nifc.gov/",resolutionRules:"Resolve YES if an official NIFC incident report lists an Oregon wildfire exceeding 100,000 acres before close; otherwise NO.",createdAt:"2026-05-12T14:00:00.000Z",featured:false,trendingScore:74},
  { id:"demo-argentina-drought-2026",onchainMarketId:1012,question:"[DEMO] Will the Argentine Pampas enter severe drought before December 31, 2026?",slug:"argentina-pampas-drought-2026-demo",description:"A fictional sample market tied to whether the national meteorological service classifies core Pampas cropland at a severe-drought level during 2026.",category:"drought",continent:"South America",country:"Argentina",region:"Pampas",latitude:-34.6,longitude:-63.0,closeTime:"2026-12-31T23:59:59.000Z",resolutionTime:"2027-01-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.55,noPrice:0.45,yesLiquidity:550,noLiquidity:450,totalVolume:3120,participants:176,resolutionSource:"Servicio Meteorol\u00F3gico Nacional (Argentina)",resolutionSourceUrl:"https://www.smn.gob.ar/",resolutionRules:"Resolve YES if an official SMN drought bulletin classifies the core Pampas cropland region at a severe-drought level before close.",createdAt:"2026-05-18T14:00:00.000Z",featured:false,trendingScore:69},
  { id:"demo-peru-elnino-2027",onchainMarketId:1013,question:"[DEMO] Will Peru declare a coastal El Ni\u00F1o before February 28, 2027?",slug:"peru-coastal-elnino-2027-demo",description:"A fictional sample market based on whether Peru's meteorological service declares coastal El Ni\u00F1o conditions.",category:"rainfall",continent:"South America",country:"Peru",region:"Peruvian coast",latitude:-12.05,longitude:-77.04,closeTime:"2027-02-28T23:59:59.000Z",resolutionTime:"2027-03-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.64,noPrice:0.36,yesLiquidity:640,noLiquidity:360,totalVolume:3480,participants:205,resolutionSource:"SENAMHI Peru official bulletins",resolutionSourceUrl:"https://www.senamhi.gob.pe/",resolutionRules:"Resolve YES if SENAMHI officially declares coastal El Ni\u00F1o conditions before close; otherwise NO.",createdAt:"2026-06-01T14:00:00.000Z",featured:true,trendingScore:85},
  { id:"demo-iberia-drought-2026",onchainMarketId:1014,question:"[DEMO] Will Andalusia be in meteorological drought before November 30, 2026?",slug:"iberia-andalusia-drought-2026-demo",description:"A fictional sample market tracking whether Spain's meteorological agency reports meteorological drought across the Andalusia region during 2026.",category:"drought",continent:"Europe",country:"Spain",region:"Andalusia",latitude:37.39,longitude:-5.99,closeTime:"2026-11-30T23:59:59.000Z",resolutionTime:"2026-12-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.69,noPrice:0.31,yesLiquidity:690,noLiquidity:310,totalVolume:3020,participants:187,resolutionSource:"Agencia Estatal de Meteorolog\u00EDa (AEMET)",resolutionSourceUrl:"https://www.aemet.es/",resolutionRules:"Resolve YES if an official AEMET report classifies Andalusia as being in meteorological drought before close.",createdAt:"2026-05-22T14:00:00.000Z",featured:false,trendingScore:72},
  { id:"demo-greece-wildfire-2026",onchainMarketId:1015,question:"[DEMO] Will Attica record a 5,000+ hectare wildfire before August 14, 2026?",slug:"greece-attica-wildfire-2026-demo",description:"A fictional sample market based on whether EFFIS records a large burned-area event in the Attica region during 2026.",category:"wildfire",continent:"Europe",country:"Greece",region:"Attica",latitude:37.98,longitude:23.73,closeTime:"2026-08-14T23:59:59.000Z",resolutionTime:"2026-08-21T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.57,noPrice:0.43,yesLiquidity:570,noLiquidity:430,totalVolume:2780,participants:169,resolutionSource:"European Forest Fire Information System (EFFIS)",resolutionSourceUrl:"https://effis.jrc.ec.europa.eu/",resolutionRules:"Resolve YES if EFFIS records a single burned-area event exceeding 5,000 hectares in Attica before close.",createdAt:"2026-05-28T14:00:00.000Z",featured:false,trendingScore:76},
  { id:"demo-sahel-drought-2026",onchainMarketId:1016,question:"[DEMO] Will the western Sahel reach IPC Crisis levels before November 30, 2026?",slug:"sahel-niger-drought-2026-demo",description:"A fictional sample market tied to whether an early-warning assessment classifies the western Sahel at a drought-driven food-security crisis level.",category:"drought",continent:"Africa",country:"Niger",region:"Western Sahel",latitude:13.51,longitude:2.11,closeTime:"2026-11-30T23:59:59.000Z",resolutionTime:"2026-12-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.74,noPrice:0.26,yesLiquidity:740,noLiquidity:260,totalVolume:2940,participants:178,resolutionSource:"Famine Early Warning Systems Network (FEWS NET)",resolutionSourceUrl:"https://fews.net/",resolutionRules:"Resolve YES if a FEWS NET assessment classifies the western Sahel at Crisis (IPC Phase 3) primarily driven by drought before close.",createdAt:"2026-06-03T14:00:00.000Z",featured:false,trendingScore:70},
  { id:"demo-horn-africa-drought-2027",onchainMarketId:1017,question:"[DEMO] Will the Horn of Africa see a below-average rainy season by January 31, 2027?",slug:"horn-of-africa-drought-2027-demo",description:"A fictional sample market based on whether a regional climate assessment reports a below-average rainy season and drought for the Horn of Africa.",category:"drought",continent:"Africa",country:"Ethiopia",region:"Horn of Africa",latitude:9.15,longitude:40.49,closeTime:"2027-01-31T23:59:59.000Z",resolutionTime:"2027-02-15T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.82,noPrice:0.18,yesLiquidity:820,noLiquidity:180,totalVolume:3360,participants:214,resolutionSource:"IGAD Climate Prediction and Applications Centre (ICPAC)",resolutionSourceUrl:"https://www.icpac.net/",resolutionRules:"Resolve YES if an official ICPAC seasonal assessment reports below-average rainfall constituting drought for the Horn of Africa before close.",createdAt:"2026-06-05T14:00:00.000Z",featured:true,trendingScore:88},
  { id:"demo-capetown-water-2027",onchainMarketId:1018,question:"[DEMO] Will Cape Town dam levels fall below 30% before March 31, 2027?",slug:"cape-town-dam-levels-2027-demo",description:"A fictional sample market tracking whether combined municipal dam storage for Cape Town drops beneath the stated threshold.",category:"drought",continent:"Africa",country:"South Africa",region:"Western Cape",latitude:-33.92,longitude:18.42,closeTime:"2027-03-31T23:59:59.000Z",resolutionTime:"2027-04-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.33,noPrice:0.67,yesLiquidity:330,noLiquidity:670,totalVolume:2050,participants:141,resolutionSource:"South African Weather Service and City of Cape Town",resolutionSourceUrl:"https://www.weathersa.co.za/",resolutionRules:"Resolve YES if the City of Cape Town's official combined dam-level report falls below 30% on any weekly release before close.",createdAt:"2026-06-08T14:00:00.000Z",featured:false,trendingScore:58},
  { id:"demo-india-monsoon-2026",onchainMarketId:1019,question:"[DEMO] Will Maharashtra record above-normal monsoon rainfall by September 30, 2026?",slug:"india-maharashtra-monsoon-2026-demo",description:"A fictional sample market based on whether India's meteorological department reports above-normal seasonal monsoon rainfall for Maharashtra.",category:"rainfall",continent:"Asia",country:"India",region:"Maharashtra",latitude:19.08,longitude:72.88,closeTime:"2026-09-30T23:59:59.000Z",resolutionTime:"2026-10-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.66,noPrice:0.34,yesLiquidity:660,noLiquidity:340,totalVolume:3610,participants:233,resolutionSource:"India Meteorological Department (IMD)",resolutionSourceUrl:"https://mausam.imd.gov.in/",resolutionRules:"Resolve YES if the IMD end-of-season report classifies Maharashtra's monsoon rainfall as above normal before close.",createdAt:"2026-05-30T14:00:00.000Z",featured:true,trendingScore:87},
  { id:"demo-japan-typhoon-2026",onchainMarketId:1020,question:"[DEMO] Will a typhoon make landfall on Honshu before October 31, 2026?",slug:"japan-honshu-typhoon-2026-demo",description:"A fictional sample market tied to whether Japan's meteorological agency records a typhoon making landfall on the island of Honshu during the season.",category:"hurricane",continent:"Asia",country:"Japan",region:"Kanto, Honshu",latitude:35.68,longitude:139.69,closeTime:"2026-10-31T23:59:59.000Z",resolutionTime:"2026-11-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.59,noPrice:0.41,yesLiquidity:590,noLiquidity:410,totalVolume:3240,participants:198,resolutionSource:"Japan Meteorological Agency (JMA)",resolutionSourceUrl:"https://www.jma.go.jp/",resolutionRules:"Resolve YES if an official JMA record identifies a typhoon making landfall on Honshu before close.",createdAt:"2026-06-10T14:00:00.000Z",featured:false,trendingScore:79},
  { id:"demo-yangtze-flooding-2026",onchainMarketId:1021,question:"[DEMO] Will the middle Yangtze exceed its warning level before August 9, 2026?",slug:"china-yangtze-flooding-2026-demo",description:"A fictional sample flood-risk market tied to a designated Yangtze River gauge.",category:"flooding",continent:"Asia",country:"China",region:"Middle Yangtze",latitude:30.59,longitude:114.3,closeTime:"2026-08-09T23:59:59.000Z",resolutionTime:"2026-08-16T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.48,noPrice:0.52,yesLiquidity:480,noLiquidity:520,totalVolume:2460,participants:162,resolutionSource:"China Ministry of Water Resources bulletins",resolutionSourceUrl:"http://www.mwr.gov.cn/",resolutionRules:"Resolve YES if the designated Hankou gauge reports a level at or above its published warning level before close.",createdAt:"2026-06-12T14:00:00.000Z",featured:false,trendingScore:71},
  { id:"demo-philippines-typhoon-2026",onchainMarketId:1022,question:"[DEMO] Will a Signal No. 3+ typhoon hit Luzon before December 31, 2026?",slug:"philippines-luzon-typhoon-2026-demo",description:"A fictional sample market based on whether PAGASA raises a high tropical-cyclone warning signal over Luzon.",category:"hurricane",continent:"Asia",country:"Philippines",region:"Luzon",latitude:14.6,longitude:120.98,closeTime:"2026-12-31T23:59:59.000Z",resolutionTime:"2027-01-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.86,noPrice:0.14,yesLiquidity:860,noLiquidity:140,totalVolume:3820,participants:247,resolutionSource:"PAGASA official tropical cyclone warnings",resolutionSourceUrl:"https://www.pagasa.dost.gov.ph/",resolutionRules:"Resolve YES if PAGASA raises Tropical Cyclone Wind Signal No. 3 or higher over any part of Luzon before close.",createdAt:"2026-06-14T14:00:00.000Z",featured:true,trendingScore:92},
  { id:"demo-queensland-cyclone-2027",onchainMarketId:1023,question:"[DEMO] Will a tropical cyclone cross the Queensland coast before March 31, 2027?",slug:"queensland-cyclone-2027-demo",description:"A fictional sample market tied to whether Australia's Bureau of Meteorology records a tropical cyclone crossing the Queensland coast.",category:"hurricane",continent:"Oceania",country:"Australia",region:"Queensland",latitude:-19.26,longitude:146.82,closeTime:"2027-03-31T23:59:59.000Z",resolutionTime:"2027-04-12T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.62,noPrice:0.38,yesLiquidity:620,noLiquidity:380,totalVolume:2720,participants:173,resolutionSource:"Australian Bureau of Meteorology cyclone archive",resolutionSourceUrl:"http://www.bom.gov.au/cyclone/",resolutionRules:"Resolve YES if an official Bureau of Meteorology record identifies a tropical cyclone crossing the Queensland coast before close.",createdAt:"2026-06-16T14:00:00.000Z",featured:false,trendingScore:78},
  { id:"demo-newzealand-heat-2027",onchainMarketId:1024,question:"[DEMO] Will a Wellington-area station record 35\u00B0C before February 28, 2027?",slug:"new-zealand-wellington-heat-2027-demo",description:"A fictional sample market based on whether a designated Wellington-area station reports an official daily maximum at or above 35\u00B0C.",category:"temperature",continent:"Oceania",country:"New Zealand",region:"Wellington",latitude:-41.29,longitude:174.78,closeTime:"2027-02-28T23:59:59.000Z",resolutionTime:"2027-03-10T18:00:00.000Z",status:"open",outcome:"unresolved",yesPrice:0.37,noPrice:0.63,yesLiquidity:370,noLiquidity:630,totalVolume:1780,participants:118,resolutionSource:"NIWA and MetService New Zealand",resolutionSourceUrl:"https://niwa.co.nz/",resolutionRules:"Resolve YES if a designated Wellington-area station publishes an official daily maximum of at least 35.0\u00B0C before close.",createdAt:"2026-06-18T14:00:00.000Z",featured:false,trendingScore:52},
]

async function main() {
  const env = loadEnv()
  const uri = env.MONGODB_URI
  if (!uri) { console.error("MONGODB_URI not found in .env"); process.exit(1) }

  console.log(`Connecting to MongoDB...`)
  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 15000 })
  await client.connect()
  console.log("Connected!\n")

  const db = client.db("climate_market")

  console.log("Creating indexes on all 7 collections...")
  await db.collection("users").createIndex({ walletAddress: 1 }, { unique: true })
  await db.collection("markets").createIndex({ marketId: 1 }, { unique: true, sparse: true })
  await db.collection("markets").createIndex({ onchainMarketId: 1 }, { unique: true, sparse: true })
  await db.collection("markets").createIndex({ status: 1 })
  await db.collection("markets").createIndex({ category: 1 })
  await db.collection("markets").createIndex({ closesAt: 1 })
  await db.collection("positions").createIndex({ walletAddress: 1 })
  await db.collection("positions").createIndex({ marketId: 1, status: 1 })
  await db.collection("positions").createIndex({ userId: 1 })
  await db.collection("transactions").createIndex({ txSignature: 1 }, { unique: true, sparse: true })
  await db.collection("transactions").createIndex({ walletAddress: 1 })
  await db.collection("transactions").createIndex({ status: 1 })
  await db.collection("resolutions").createIndex({ marketId: 1 }, { unique: true })
  await db.collection("market_prices").createIndex({ marketId: 1, timestamp: 1 })
  await db.collection("auth_challenges").createIndex({ walletAddress: 1 })
  await db.collection("auth_challenges").createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 })
  console.log("Indexes ready.\n")

  console.log(`Seeding ${markets.length} demo markets...`)
  for (const m of markets) {
    await db.collection("markets").updateOne(
      { marketId: m.id },
      {
        $set: {
          marketId: m.id, onchainMarketId: m.onchainMarketId,
          title: m.question, question: m.question, description: m.description, slug: m.slug,
          category: m.category, continent: m.continent, country: m.country ?? null, region: m.region,
          latitude: m.latitude, longitude: m.longitude,
          resolutionSource: m.resolutionSource, resolutionSourceUrl: m.resolutionSourceUrl, resolutionRules: m.resolutionRules,
          status: m.status, outcome: m.outcome,
          yesPrice: m.yesPrice, noPrice: m.noPrice, yesLiquidity: m.yesLiquidity, noLiquidity: m.noLiquidity,
          totalVolume: m.totalVolume, participants: m.participants,
          featured: m.featured, trendingScore: m.trendingScore,
          openAt: new Date(m.createdAt), closesAt: new Date(m.closeTime), resolvesAt: new Date(m.resolutionTime ?? m.closeTime),
          createdAt: new Date(m.createdAt),
        }
      },
      { upsert: true },
    )
  }
  console.log("Markets seeded.\n")

  // Verify
  const count = await db.collection("markets").countDocuments()
  console.log(`markets collection: ${count} documents`)

  const byStatus = await db.collection("markets").aggregate([
    { $group: { _id: "$status", count: { $sum: 1 } } }
  ]).toArray()
  console.log("  by status:", byStatus.map(s => `${s._id}:${s.count}`).join(", "))

  // Seed some sample positions for the demo wallet
  const testWallet = "8qFS3dgQGZ614c2owwobfT5qjZnSxMgb6Wg2abh7b75i"
  await db.collection("users").updateOne(
    { walletAddress: testWallet },
    { $setOnInsert: { walletAddress: testWallet, createdAt: new Date() }, $set: { lastLoginAt: new Date() } },
    { upsert: true },
  )
  const user = await db.collection("users").findOne({ walletAddress: testWallet })
  console.log(`\nusers collection: wallet ${user.walletAddress} ready`)

  // Insert sample positions
  const existingPositions = await db.collection("positions").countDocuments()
  if (existingPositions === 0) {
    const samplePositions = [
      { walletAddress: testWallet, marketDocId: "demo-fl-hurricane-2026", onchainMarketId: 1001, marketQuestion: markets[0].question, side: "yes", amountSol: 0.5, amountLamports: "500000000", estimatedPayoutSol: 1.1628, estimatedPayoutLamports: "1162800000", status: "open", txSignature: "3FJ7fk2e93NRkzrJ41Qy7L8B6EbKSkSWBr2ryJXgrQnQmodQbv7rUAGNvfp9z4oPR6fKKEb37MPkDsGPvSquHHL2", createdAt: new Date() },
      { walletAddress: testWallet, marketDocId: "demo-amazon-dry-season-2026", onchainMarketId: 1008, marketQuestion: markets[7].question, side: "no", amountSol: 0.3, amountLamports: "300000000", estimatedPayoutSol: 0.5556, estimatedPayoutLamports: "555600000", status: "claimable", txSignature: "3dNnC3pGB6SAeQL4BpkJknmMHp8HsJha8EbqnAmK3cY4tHL2x1TWwxQVHFQ9APpnYk6HuUUhjuCvBdxgEibFu4aW", createdAt: new Date() },
      { walletAddress: testWallet, marketDocId: "demo-netherlands-coastal-flood-2026", onchainMarketId: 1009, marketQuestion: markets[8].question, side: "yes", amountSol: 0.12, amountLamports: "120000000", estimatedPayoutSol: 0.4138, estimatedPayoutLamports: "413800000", status: "refundable", txSignature: "5yHzW49dFwtrz3AGd6mzv76147ugrLZS1dWxhBDW9spK3Z7C8PLXvUu5qr2EhzwsGwxoNGRBUdzrmUF5pFPBtazb", createdAt: new Date() },
    ]
    await db.collection("positions").insertMany(samplePositions)
    console.log(`positions collection: ${samplePositions.length} sample positions seeded`)
  } else {
    console.log(`positions collection: ${existingPositions} existing positions`)
  }

  await client.close()
  console.log("\nDone - cloud database fully seeded.")
}

main().catch((err) => { console.error("FAIL:", err.message); process.exit(1) })
